### ISSUE TITLE
Update url 

### ISSUE THREAD

**Issue by nicogodet** [conda-forge/libmed-feedstock#45]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

New url should be `http://files.salome-platform.org/Salome/medfile/med-{{ version }}.tar.gz`
Ref http://www.opentelemac.org/index.php/kunena/12-linux-version/14414-med-4-1-0-tar-gz-file-not-available-on-salome-platform#43460

### Installed packages

```shell
not needed
```

### Environment info

```shell
not needed
```

**Comment by ldallolio** [comment]
Hi, thanks for the heads up! I built a new (probably better) package with the new link
Have a nice day :)
